# -*- mode: ruby -*-
# vi: set ft=ruby :

WORKER_COUNT = 2

Vagrant.configure("2") do |config|
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable General Ansible Provisioning for all VMs
  config.vm.provision :ansible do |a|
    a.compatibility_mode = "2.0"
    a.playbook = "./playbooks/general.yaml"
  end

  # Define the Controller VM
  config.vm.define "ctrl" do |ctrl|
    ctrl.vm.box = "bento/ubuntu-24.04"
    
    ctrl.vm.provider "virtualbox" do |v|
      v.name = "ctrl"
      v.memory = 4096
      v.cpus = 1
    end

    ctrl.vm.network "private_network", ip: "192.168.56.100"

    ### When the controller playbook is ready, uncomment this section. ###
    # ctrl.vm.provision :ansible do |a|
    #   a.compatibility_mode = "2.0"
    #   a.playbook = "./playbooks/ctrl.yaml"
    # end
  end

  # Define Worker Node VMs dynamically
  (1..WORKER_COUNT).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "bento/ubuntu-24.04"

      node.vm.provider "virtualbox" do |v|
        v.name = "node-#{i}"
        v.memory = 6144
        v.cpus = 2
      end

      node.vm.network "private_network", ip: "192.168.56.#{100 + i}"
      
      ### When the node playbook is ready, uncomment this section. ###
      # node.vm.provision :ansible do |a|
      #   a.compatibility_mode = "2.0"
      #   a.playbook = "./playbooks/node.yaml"
      # end
    end
  end
end
