{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.model.name }}-dr
spec:
  host: {{ .Values.model.name }}
  subsets:

    # Stable (always)
    - name: v1
      labels:
        version: v1

  {{- if .Values.model.canary.enabled }}
    # Canary subset
    - name: {{ .Values.model.canary.tag }}
      labels:
        version: {{ .Values.model.canary.tag }}
  {{- end }}
  
  {{- if .Values.model.shadow.enabled }}
    # Shadow subset
    - name: {{ .Values.model.shadow.tag }}
      labels:
        version: {{ .Values.model.shadow.tag }}
  {{- end }}
{{- end }}
