{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.model.name }}-vs
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.model.name }}
  http:
  {{- if .Values.model.canary.enabled }}

    # v2 to v2 plus shadow if enabled
    - match:
      - sourceLabels:
          version: v2
      route:
        - destination:
            host: {{ .Values.model.name }}
            subset: {{ .Values.model.canary.tag }}
          weight: 100
      {{- if .Values.model.shadow.enabled }}
      mirror:
        host: {{ .Values.model.name }}
        subset: {{ .Values.model.shadow.tag }}
      mirrorPercentage:
        value: {{ .Values.istio.shadow.mirrorPercentage | default 100 }}
      {{- end }}

    # v1 to v1 plus shadow if enabled
    - route:
      - destination:
          host: {{ .Values.model.name }}
          subset: v1
        weight: 100
      {{- if .Values.model.shadow.enabled }}
      mirror:
        host: {{ .Values.model.name }}
        subset: {{ .Values.model.shadow.tag }}
      mirrorPercentage:
        value: {{ .Values.istio.shadow.mirrorPercentage | default 100 }}
      {{- end }}

  {{- else }}

    # Route only to stable v1 and shadow if enabled
    - route:
      - destination:
          host: {{ .Values.model.name }}
          subset: v1
        weight: 100
      {{- if .Values.model.shadow.enabled }}
      mirror:
        host: {{ .Values.model.name }}
        subset: {{ .Values.model.shadow.tag }}
      mirrorPercentage:
        value: {{ .Values.istio.shadow.mirrorPercentage | default 100 }}
      {{- end }}

  {{- end }}
{{- end }}
