apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.model.name }}-pvc
  labels:
    app: {{ .Values.model.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.model.storage }}
