apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.app.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name }}
                port:
                  number: {{ .Values.app.port }}

          # -----------------------------------------
          # Monitoring: expose /metrics via Ingress
          # -----------------------------------------
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name }}
                port:
                  name: metrics