{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app.name }}-sm
  labels:
    app: {{ .Values.app.name }}
    team: doda2025-team20      # Matches Prometheus selector
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
{{- end }}