apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.adminSecretName }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.adminUser | quote }}
  admin-password: {{ .Values.grafana.adminPassword | quote }}