apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-grafana
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana