{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.model.name }}-dr
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  host: {{ .Values.model.name }}
  subsets:
  - name: v1
    labels:
      version: v1
  {{- if .Values.istio.canary.enabled }}
  - name: v2
    labels:
      version: v2
  {{- end }}
{{- end }}