{{- if .Values.istio.enabled }}
# VirtualService to expose /metrics endpoint via IngressGateway
# Required by rubric: "The /metrics endpoint of the frontend-service is reachable through the Ingress"
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}-metrics-vs
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  gateways:
  - {{ .Values.istio.gateway.name }}
  hosts:
  {{- range .Values.istio.gateway.hosts }}
  - {{ . | quote }}
  {{- end }}
  http:
  # Route /metrics to app-service (v1 only for simplicity)
  - match:
    - uri:
        exact: /metrics
    route:
    - destination:
        host: {{ .Values.app.name }}
        port:
          number: {{ .Values.app.port }}
{{- end }}