{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.model.name }}-vs
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.model.name }}
  http:

  {{- if .Values.istio.canary.enabled }}

    # -----------------------
    # Canary deployment
    # -----------------------
    - route:
        - destination:
            host: {{ .Values.model.name }}
            subset: v1
          weight: {{ .Values.istio.canary.stableWeight }}
        - destination:
            host: {{ .Values.model.name }}
            subset: v2
          weight: {{ .Values.istio.canary.canaryWeight }}

  {{- else if .Values.istio.shadow.enabled }}

    # -----------------------
    # Shadow launch (traffic mirroring)
    # -----------------------
    - route:
        - destination:
            host: {{ .Values.model.name }}
            subset: v1
          weight: 100
      mirror:
        destination:
          host: {{ .Values.model.name }}
          subset: {{ .Values.model.shadow.tag }}
      mirrorPercentage:
        value: {{ .Values.istio.shadow.mirrorPercentage }}

  {{- else }}

    # -----------------------
    # Default: stable only
    # -----------------------
    - route:
        - destination:
            host: {{ .Values.model.name }}
            subset: v1
          weight: 100

  {{- end }}
{{- end }}