{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ .Values.app.name }}-dr
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  host: {{ .Values.app.name }}
  {{- if .Values.istio.canary.stickySession.enabled }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: {{ .Values.istio.canary.stickySession.cookieName }}
          ttl: 3600s
  {{- end }}
  subsets:
    - name: v1
      labels:
        version: v1
    {{- if .Values.istio.canary.enabled }}
    - name: v2
      labels:
        version: v2
    {{- end }}
{{- end }}
