{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.model.name }}-vs
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ .Values.model.name }}
  http:
  {{- if .Values.istio.canary.enabled }}
  # Route from v2 app to v2 model
  - match:
    - sourceLabels:
        version: v2
    route:
    - destination:
        host: {{ .Values.model.name }}
        subset: v2
  {{- end }}
  # Default route to v1 model
  - route:
    - destination:
        host: {{ .Values.model.name }}
        subset: v1
{{- end }}