{{- if .Values.istio.enabled }}
# VirtualService to expose Grafana via IngressGateway
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}-grafana-vs
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  gateways:
  - {{ .Values.istio.gateway.name }}
  hosts:
  {{- range .Values.istio.gateway.hosts }}
  - {{ . | quote }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: /grafana
    route:
    - destination:
        host: {{ .Release.Name }}-grafana
        port:
          number: 80
{{- end }}