{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.app.name }}-dr
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  # Use fully-qualified service name for reliable Istio routing
  host: {{ .Values.app.name }}.{{ .Release.Namespace }}.svc.cluster.local

  {{- if .Values.istio.canary.stickySession.enabled }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: {{ .Values.istio.canary.stickySession.cookieName }}
          ttl: 3600s
  {{- end }}

  # Subsets correspond to application versions
  subsets:
    - name: v1
      labels:
        version: v1

    {{- if .Values.istio.canary.enabled }}
    - name: v2
      labels:
        version: v2
    {{- end }}
{{- end }}