apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.model.name }}
  labels:
    app: {{ .Values.model.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.model.port }}
      targetPort: {{ .Values.model.port }}
  selector:
    app: {{ .Values.model.name }}
