apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app.name }}-monitor
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
    app: {{ .Values.app.name }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    relabelings:
    # Add version label from pod
    - sourceLabels: [__meta_kubernetes_pod_label_version]
      targetLabel: version
    # Add pod name
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod